// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: bank_account_transaction.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BankAccountTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *BankAccountTransaction) Reset() {
	*x = BankAccountTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_account_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BankAccountTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccountTransaction) ProtoMessage() {}

func (x *BankAccountTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccountTransaction.ProtoReflect.Descriptor instead.
func (*BankAccountTransaction) Descriptor() ([]byte, []int) {
	return file_bank_account_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *BankAccountTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BankAccountTransaction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BankAccountTransaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BankAccountId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BankAccountId) Reset() {
	*x = BankAccountId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_account_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BankAccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccountId) ProtoMessage() {}

func (x *BankAccountId) ProtoReflect() protoreflect.Message {
	mi := &file_bank_account_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccountId.ProtoReflect.Descriptor instead.
func (*BankAccountId) Descriptor() ([]byte, []int) {
	return file_bank_account_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *BankAccountId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_bank_account_transaction_proto protoreflect.FileDescriptor

var file_bank_account_transaction_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x22, 0x54, 0x0a, 0x16, 0x42,
	0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x25, 0x0a, 0x0d, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x79, 0x0a, 0x1a, 0x42, 0x61, 0x6e, 0x6b,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x5b, 0x0a, 0x1a, 0x67, 0x65, 0x74, 0x42, 0x61, 0x6e,
	0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65,
	0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x21,
	0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_bank_account_transaction_proto_rawDescOnce sync.Once
	file_bank_account_transaction_proto_rawDescData = file_bank_account_transaction_proto_rawDesc
)

func file_bank_account_transaction_proto_rawDescGZIP() []byte {
	file_bank_account_transaction_proto_rawDescOnce.Do(func() {
		file_bank_account_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_bank_account_transaction_proto_rawDescData)
	})
	return file_bank_account_transaction_proto_rawDescData
}

var file_bank_account_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bank_account_transaction_proto_goTypes = []interface{}{
	(*BankAccountTransaction)(nil), // 0: ecommerce.BankAccountTransaction
	(*BankAccountId)(nil),          // 1: ecommerce.BankAccountId
}
var file_bank_account_transaction_proto_depIdxs = []int32{
	1, // 0: ecommerce.BankAccountTransactionInfo.getBankAccountTransactions:input_type -> ecommerce.BankAccountId
	0, // 1: ecommerce.BankAccountTransactionInfo.getBankAccountTransactions:output_type -> ecommerce.BankAccountTransaction
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bank_account_transaction_proto_init() }
func file_bank_account_transaction_proto_init() {
	if File_bank_account_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bank_account_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BankAccountTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_account_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BankAccountId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bank_account_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bank_account_transaction_proto_goTypes,
		DependencyIndexes: file_bank_account_transaction_proto_depIdxs,
		MessageInfos:      file_bank_account_transaction_proto_msgTypes,
	}.Build()
	File_bank_account_transaction_proto = out.File
	file_bank_account_transaction_proto_rawDesc = nil
	file_bank_account_transaction_proto_goTypes = nil
	file_bank_account_transaction_proto_depIdxs = nil
}
